# Generated by Django 2.1.5 on 2019-01-22 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Budget Name', max_length=180)),
                ('total_budget', models.FloatField(blank=True)),
                ('remaining_budget', models.FloatField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'WITHDRAWAL'), ('deposit', 'DEPOSIT')], max_length=25)),
                ('amount', models.FloatField(default=0)),
                ('description', models.CharField(default='Transaction Description', max_length=180)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_tool.Budget')),
            ],
        ),
    ]
